--- 
input_dir: ./input
output_dir: ./output
max_num_objects: 2
metric: rsme

confidence_threshold: 0.75
iou_threshold: 0.25

# Column Configurations
annotations_col: annotations
image_col: image
masks_col: stateMasks

# Drawing Options 
target_label: mainPlate
draw_boundings: On
draw_masks: Off
draw_centers: On
draw_contrail: Off
draw_frame_num: On
fps: 30
buffer: 64